require("config.setters")
require("config.mapping")
require("config.cmp")
require("plugins.lsp")
require("plugins.tree")
require("plugins.theme")
require("plugins.telescope")
require("plugins.lualine")
require("plugins.neoscroll")

